# Generated by Django 5.1.6 on 2025-03-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('ajout', 'Ajout'), ('modification', 'Modification'), ('suppression', 'Suppression')], max_length=20)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('matricule', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('droit_ancien', models.BooleanField()),
                ('droit_nouveau', models.BooleanField()),
                ('utilisateur', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('adresse', models.TextField(blank=True, null=True)),
                ('droit_inscription', models.BooleanField()),
            ],
        ),
    ]
