# Generated by Django 5.1.6 on 2025-03-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditinscription',
            name='droit_ancien',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
