# Generated by Django 5.1.6 on 2025-03-13 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditinscription',
            options={'verbose_name': "Audit d'Inscription", 'verbose_name_plural': 'Audits des Inscriptions'},
        ),
        migrations.AlterModelOptions(
            name='inscription',
            options={'verbose_name': 'Inscription', 'verbose_name_plural': 'Inscriptions'},
        ),
        migrations.AlterModelOptions(
            name='statistiqueinscription',
            options={'verbose_name': "Statistique d'Inscription", 'verbose_name_plural': 'Statistiques des Inscriptions'},
        ),
        migrations.AlterField(
            model_name='auditinscription',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
