# Generated by Django 5.1.6 on 2025-03-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0002_alter_auditinscription_droit_ancien'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditinscription',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditinscription',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditinscription',
            name='droit_inscription',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='auditinscription',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
