# Generated by Django 5.1.6 on 2025-03-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0003_auditinscription_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditinscription',
            name='droit_nouveau',
            field=models.BooleanField(blank=True, max_length=100, null=True),
        ),
    ]
