# Generated by Django 5.1.6 on 2025-03-03 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0004_alter_auditinscription_droit_nouveau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditinscription',
            name='droit_ancien',
        ),
        migrations.RemoveField(
            model_name='auditinscription',
            name='droit_nouveau',
        ),
        migrations.AddField(
            model_name='auditinscription',
            name='inscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inscriptions.inscription'),
        ),
        migrations.AlterField(
            model_name='auditinscription',
            name='adresse',
            field=models.CharField(default='Adresse inconnue', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditinscription',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='auditinscription',
            name='date_naissance',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='auditinscription',
            name='droit_inscription',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auditinscription',
            name='matricule',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auditinscription',
            name='prenom',
            field=models.CharField(default='Inconnu', max_length=100),
        ),
        migrations.AlterField(
            model_name='auditinscription',
            name='type_action',
            field=models.CharField(choices=[('AJOUT', 'Ajout'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='droit_inscription',
            field=models.BooleanField(default=True),
        ),
    ]
