# Generated by Django 5.1.6 on 2025-03-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0005_remove_auditinscription_droit_ancien_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=200)),
                ('droit_ancien', models.CharField(max_length=100)),
                ('droit_nouveau', models.CharField(max_length=100)),
                ('type_action', models.CharField(max_length=100)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
